### Mini - Batch Gradient Descent

In [2]:
from sklearn.datasets import load_diabetes

import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_diabetes(return_X_y = True)

In [4]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [5]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
x_train.shape

(353, 10)

In [7]:
y_train.shape

(353,)

In [8]:
reg = LinearRegression()

In [11]:
reg.fit(x_train,y_train)

LinearRegression()

In [12]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [13]:
reg.intercept_

151.88331005254167

In [14]:
y_pred = reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [27]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None 
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,x_train,y_train):
        # init your coef 
        self.intercept_ = 0 
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(x_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(x_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
                
        print(self.intercept_,self.coef_)        
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [36]:
mbr = MBGDRegressor(batch_size=int(x_train.shape[0]/10),learning_rate=0.01,epochs=55)

In [37]:
mbr.fit(x_train,y_train)

153.20356254423316 [  51.4537114   -82.02355014  361.31024726  261.28406612   15.51486788
  -34.11239565 -174.79019611  133.32531595  335.51941111  127.62820912]


In [38]:
y_pred = mbr.predict(x_test)

In [39]:
r2_score(y_test,y_pred)

0.4377137294375816

#### Calculate Mini - Batch regressor -> by using of SGDRegressor

In [41]:
from sklearn.linear_model import SGDRegressor

In [52]:
sgd = SGDRegressor(learning_rate = 'constant',eta0 = 0.1)

In [53]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [54]:
sgd.coef_

array([  39.50424031,  -69.29535041,  328.57890508,  241.64800209,
         16.20826106,  -33.05040427, -166.23990607,  123.07770417,
        324.43728327,  134.24189841])

In [55]:
sgd.intercept_

array([148.7726534])

In [56]:
y_pred = sgd.predict(x_test)

In [57]:
r2_score(y_test,y_pred)

0.4300334687218119